name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-dashboard-backend:v0.0.1 ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-dashboard-backend:v0.0.1

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-dashboard-frontend:v0.0.1 ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-dashboard-frontend:v0.0.1
